In [5]:
import tkinter as tk
import sqlite3
import pandas as pd
from tkinter import ttk
main = tk.Tk()
subscription_entry=tk.IntVar()
payment_type = ttk.Combobox(main)
payment_type['values'] = ('Visa','American Express','MasterCard','Discover')
card_var = tk.StringVar()
sec_var=tk.StringVar()
user_var=tk.StringVar()
label = tk.Label(main, text="Hello there! Would you like to buy our GymGains Tracker software subscription?")
label.pack()
sql_connect = sqlite3.connect('Subscribers.db')
cur = sql_connect.cursor() 
cur.execute('''
CREATE TABLE IF NOT EXISTS app_data (
    name TEXT,
    sub INTEGER
    )
''')
sql_connect.commit()
sql_connect.commit()
def Subscript():
    label = tk.Label(main, text="How many months of AMAZING GAINS would you like?")
    label.pack()
    sub_entry = tk.Entry(main,textvariable =subscription_entry ,font=('arial',14,'normal'))
    sub_entry.pack()
    submit_button = tk.Button(main,text="Submit",command = SubCalc)
    submit_button.pack()
def SubCalc():
    months= int(subscription_entry.get())
    if months>6:
            subtotal=round((months*8.3)-(months*8.3)*.10)
            subtotal=str(subscription_entry.get())+' month subscription, it will be $'+str(subtotal)
            sub='Thank you for your '+ subtotal
            sub_label=tk.Label(main, text=sub , font = ('arial',14,'normal'))
            sub_label.pack()
    elif months <= 6:
            subtotal=round(months*8.3)
            subtotal=str(subscription_entry.get())+' month subscription, it will be $'+str(subtotal)
            sub='Thank you for your '+ subtotal
            sub_label=tk.Label(main, text=sub , font = ('arial',14,'normal'))
            sub_label.pack() 
    bank()
def bank():
    bank = tk.Label(main, text="Which credit card processor will you be using")
    payment_type.set('bank')
    bank.pack()
    payment_type.pack()
    submit_button = tk.Button(main,text="Submit",command = cardInfo)
    submit_button.pack()
def cmon():
    endMessage= tk.Label(main, text="We hope you change your mind")
    endMessage.pack()
    exit_button= tk.Button(main,text='Exit',command=main.destroy)
    exit_button.pack()
def cardChecker():
    card = card_var.get()
    CVV = sec_var.get()
    if  card.isdigit()==True and len(card)==9:
        if CVV.isdigit() and len(CVV)==3:
            thx()
        else:
            error= tk.Label(main, text="Please reenter the CVV correctly", width=40, height=3)
            error.pack()
    else:
        error= tk.Label(main, text="Please reenter the 9 card numbers correctly", width=40, height=3)
        error.pack()
def cardInfo():
    bank="You chose: "+ payment_type.get()
    bank_chosen = tk.Label(main, text=bank, font=('arial',14,'normal'))
    bank_chosen.pack()
    user= tk.Label(main, text="What is the name on the card?", width=35, height=5)
    user.pack()
    user_entry = tk.Entry(main,textvariable = user_var,font=('arial',14,'normal'))
    user_entry.pack()
    digits= tk.Label(main, text="Enter the 9 digits of your card.", width=35, height=5)
    digits.pack()
    card_entry = tk.Entry(main,textvariable = card_var,font=('arial',14,'normal'))
    card_entry.pack()
    sec_label= tk.Label(main, text="Enter the 3 CVV numbers.", width=35, height=5)
    sec_label.pack()
    sec_entry = tk.Entry(main,textvariable = sec_var,font=('arial',14,'normal'))
    sec_entry.pack()
    button = tk.Button(main, text="Submit", command = cardChecker)
    button.pack()
def thx():
    thx = tk.Toplevel(main)
    thx.title('Thank You!')
    sub='Thank you, '+str(user_var.get())+' have a great day!'
    thx_label=tk.Label(thx, text=sub , font = ('arial',20,'normal'))
    thx_label.pack()
    button = tk.Button(main, text="Exit", command = main.destroy)
    button.pack()
    Subscribers()
def Subscribers():
    name=user_var.get()
    sub=subscription_entry.get()
    query = "INSERT INTO app_data (name, sub) VALUES (?, ?)"
    cur.execute(query, (name, sub))
    sql_connect.commit()
button = tk.Button(main, text="Buy GAINS", command = Subscript)
button.pack()
button = tk.Button(main, text="Cancel", command = cmon )
button.pack()

main.mainloop()

In [6]:
pd.read_sql_query('''
    SELECT * FROM app_data;
    ''', sql_connect)

  name  sub
0  bob   35
1  bob   45